# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i0HVf3daMB5JbraAPN9cANM46M2rjSbq
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile calculadora.py
# 
# def soma (a, b):
#   return a + b
# 
# 
# def subtracao(a, b):
#   return a - b
# 
# 
# def multiplicacao(a, b):
#   return a * b
# 
# 
# def divisao(a, b):
#   if b == 0:
#     raise ValueError("Não é possível dividir por zero")
# 
#   return a / b

# Commented out IPython magic to ensure Python compatibility.
# %%writefile test_calculadora.py
# 
# import unittest
# 
# from calculadora import soma
# from calculadora import subtracao
# from calculadora import multiplicacao
# from calculadora import divisao
# 
# class TestCalculadora(unittest.TestCase):
# 
#   def test_soma(self):
#     self.assertEqual(soma(10, 5), 15)
# 
#   def test_subtracao(self):
#     self.assertEqual(subtracao(10, 5), 5)
# 
#   def test_multiplicacao(self):
#     self.assertEqual(multiplicacao(10, 5), 50)
# 
#   def test_divisao(self):
#     self.assertEqual(divisao(10, 5), 2)

!python -m unittest test_calculadora.py -v

!ls -l